name: nice_step_indicator
description: A package for nice step indicators in your app
version: 0.1.0
homepage: https://github.com/ethiel97/nice_step_indicator
repository: https://github.com/ethiel97/nice_step_indicator
license: MIT
issue_tracker: https://github.com/ethiel97/nice_step_indicator/issues

environment:
  sdk: ^3.4.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter