name: nice_step_indicator
description: A customizable and animated Flutter package for creating beautiful step indicators with support for various styles, colors, and progress tracking
version: 0.2.0
homepage: https://github.com/ethiel97/nice_step_indicator
repository: https://github.com/ethiel97/nice_step_indicator
license: MIT
topics: [UI, Progress indicator]

screenshots:
  - description: Nice step indicator
    path: assets/demo.png


environment:
  sdk: ^3.5.4
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
